apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: b90f7d6c362232c633e788bae53af62a992a1b4aeb08bf79586b2d3228ce8f4a
    cni.projectcalico.org/podIP: 10.1.124.208/32
    cni.projectcalico.org/podIPs: 10.1.124.208/32
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"run":"webapp"},"name":"webapp-declarative","namespace":"default"},"spec":{"containers":[{"image":"k8smaestro/web-app:1.0","name":"webapp","ports":[{"containerPort":80}]}]}}
  creationTimestamp: "2024-02-03T22:08:57Z"
  labels:
    run: webapp
  name: webapp-declarative
  namespace: default
  resourceVersion: "10834"
  uid: f97563a1-2f8a-4be2-a1ad-11f856ad77a3
spec:
  containers:
  - image: k8smaestro/web-app:1.0
    imagePullPolicy: IfNotPresent
    name: webapp
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jhnwj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: fedora
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-jhnwj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-03T22:08:57Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-03T22:08:58Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-03T22:08:58Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-03T22:08:57Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://50ef33d52c82199190ee3164835ec4ffedc7009707d9d61197c928cf2bd064a8
    image: docker.io/k8smaestro/web-app:1.0
    imageID: docker.io/k8smaestro/web-app@sha256:34be68282713beb3c61abeaa913e4c73db65c09d474e151571316d53151b46b5
    lastState: {}
    name: webapp
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-03T22:08:58Z"
  hostIP: 192.168.1.110
  phase: Running
  podIP: 10.1.124.208
  podIPs:
  - ip: 10.1.124.208
  qosClass: BestEffort
  startTime: "2024-02-03T22:08:57Z"
