apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-nginx-pods
  template:
    metadata:
      name: task-nginx-pod
      labels:
          app: task-nginx-pods
      annotations:
        container.apparmor.security.beta.kubernetes.io/nginx: runtime/default
    spec:
      securityContext:
        runAsUser: 10000
        runAsNonRoot: true
        runAsGroup: 10001
        fsGroup: 10001
      containers:
      - name: nginx
        image : nginxinc/nginx-unprivileged:1.27.2
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - all
          privileged: false
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: 100Mi
            cpu: 200m
          limits:
            memory: 200Mi
            cpu: 500m
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 1
          periodSeconds: 10