apiVersion: v1
kind: Service
metadata:
    name: odoo-svc
    namespace: odoo
spec:
    selector:
        app: odoo
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8069
