apiVersion: apps/v1
kind: Deployment
metadata:
    name: busybox
spec:
    replicas: 1
    selector:
        matchLabels:
            app: busybox
    template:
        metadata:
            labels:
                app: busybox
        spec:
            containers:
                -   name: busybox-payment
                    image: busybox:1.36.0
                    command:
                        - sh
                        - -c
                        - |
                            echo "MERCHANT_ID: $MERCHANT_ID"
                            echo "PAYMENT_GATEWAY_API_KEY: $PAYMENT_GATEWAY_API_KEY"
                    env:
                        -   name: MERCHANT_ID
                            valueFrom:
                                configMapKeyRef:
                                    name: configmapss31
                                    key: merchantID
                        -   name: PAYMENT_GATEWAY_API_KEY
                            valueFrom:
                                secretKeyRef:
                                    name: secretmapss31
                                    key: paymentApiKey
