apiVersion: apps/v1
kind: Deployment
metadata:
    name: odoo-deployment
    namespace: odoo
spec:
    replicas: 1
    selector:
        matchLabels:
            app: odoo
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0 
        maxSurge: 1
    template:
        metadata:
            labels:
                app: odoo
        spec:
            volumes: 
                - name: odoo-bitnami
                  persistentVolumeClaim:
                    claimName: odoo-pvc
            containers:
                - name: odoo
                  image: docker.io/bitnami/odoo:16
                  ports:
                      - containerPort: 8069
                  env:
                      - name: ODOO_DATABASE_HOST
                        value: 'postgresql.odoo.svc.cluster.local'
                      - name: ODOO_DATABASE_PORT_NUMBER
                        value: '5432'
                      - name: ODOO_DATABASE_USER
                        valueFrom:
                            configMapKeyRef:
                                name: odoo-config-map
                                key: dbUser
                      - name: ODOO_DATABASE_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: odoo-secret
                                key: dbPassword
                      - name: ODOO_DATABASE_NAME
                        value: 'k8smaestro'
                  volumeMounts:
                    - mountPath: /bitnami/odoo
                      name: odoo-bitnami
                  resources:
                    requests:
                      cpu: 100m
                      memory: 150Mi
                    limits:
                      cpu: 150m
                      memory: 250Mi