apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgresql-deployment
    namespace: odoo
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgresql
    template:
        metadata:
            labels:
                app: postgresql
        spec:
            containers:
                - name: postgres
                  image: docker.io/bitnami/postgresql:15
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRESQL_DATABASE
                        value: k8smaestro
                      - name: POSTGRESQL_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: odoo-secret
                                key: dbPassword
                      - name: POSTGRESQL_USERNAME
                        valueFrom:
                            configMapKeyRef:
                                name: odoo-config-map
                                key: dbUser
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /bitnami/postgresql
                  resources:
                      requests:
                          cpu: 100m
                          memory: 100Mi
                      limits:
                          cpu: 150m
                          memory: 250Mi
            volumes:
                - name: postgres-storage
                  emptyDir: {}
