apiVersion: v1
kind: Service
metadata:
    name: postgresql
    namespace: odoo
spec:
    selector:
        app: postgresql
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
